### ISSUE TITLE
Create a "thinking / loading" indicator for things that might take a long time (network requests, long winded data crunching)

### ISSUE THREAD

**Issue by louh** [opentraffic/analyst-ui#62]
Something like the one on the [Maps product page](https://mapzen.com/products/maps/), off in the corner and pretty unobtrusive.

![screenshot 2017-08-10 11 06 37](https://user-images.githubusercontent.com/2553268/29177223-22d9bae4-7dbc-11e7-8329-36ad6d632a47.png)

I tried googling for good examples of video game loading indicators (not loading screens) and came up short, but I'm pretty sure they exist.

**Comment by mkong0216** [comment]
Couple of questions. 

1. When you say 'video game loading indicators', do you mean the loading bar ones? Are we using loading bar ones or the circle ones? I'm asking this because semantic-ui-react has loading icons but they just rotate in circles and if those aren't what we want I can start looking for other ones. 

2. How are we going to connect all the things that need an indicator to this loading indicator component? Is it one loading indicator for all these things or each thing that requires a long time to think gets its own indicator? If that makes sense... I'm trying to think ahead on how we would start/stop the loading.

**Comment by louh** [comment]
1. Semantic UI's stock rotating circles are great!
2. We should only have one loading component and it only needs to know things: "am I on?" and "am I off?" The things that need to turn on the loading indicator will send out "hey Loading indicator, turn on" and "hey Loading indicator, turn off". Redux store is a good place to send this to, so there's just one place that records what state the Loading indicator is in. There is just one complexity: if two things tell Loading to turn on. One finishes first, and tells Loading to turn off. So Loading turns off. In the meantime number two is still loading, but Loading has already turned itself off. One way to solve this is to set up a counter of some kind so that Loading only turns off only after all the "Hey Loading, turn off" messages get sent.

**Comment by mkong0216** [comment]
Ahhhh okay got it. This loading indicator would also be found on the corner of the map right? 
Mind if I have a go at this?

**Comment by louh** [comment]
Yep, pick a corner! It's all yours!
